// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TestPlugin","status":true,"description":"","parameters":{}},
{"name":"battleList","status":true,"description":"","parameters":{}},
{"name":"Tetris","status":true,"description":"","parameters":{}}
];
